[package]
name = "day10"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.14.0"
nalgebra = "0.34.1"
regex = "1.12.2"
