[package]
name = "day12"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.6"
regex = "1.12.2"
utils = { version = "0.1.0", path = "../../rust-utils" }
